dist: xenial

language: go
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'
go:
  - 1.12.x
git:
  depth: 1
notifications:
  email: false

script:
  - go mod init
  - go build -o example/example example/example.go
