dist: xenial

language: go

env:
  - GO111MODULE=on

services:
  - docker

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

before_install:
- docker run --name test_sshd -d --rm -p 50022:22 -v ${PWD}/.docker/.ssh:/root/.ssh rastasheep/ubuntu-sshd
- docker exec test_sshd chown root:root /root/.ssh/authorized_keys
- docker exec test_sshd chmod 700 /root/.ssh
- docker exec test_sshd chmod 600 /root/.ssh/authorized_keys

script:
  - go build -o example/example example/example.go
  - ls -la
  - ssh -v -o 'StrictHostKeyChecking no' -i .docker/.ssh/id_rsa -p 50022 root@127.0.0.1 hostname
  - go test -run CircleCI
