version: 2.1

jobs:
  build-go-latest:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/blacknon/go-scplib
    steps:
      - checkout
      - run: go mod init
      - run: go build example/example.go -o example1
    environment:
      GO111MODULE: "on"
workflows:
  version: 2
  build:
    jobs:
      - build-go-latest
