version: 2.1

jobs:
  build-go-latest:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/blacknon/go-scplib
    steps:
      - checkout
      - run: go get -u
workflows:
  version: 2
  build:
    jobs:
      - build-go-latest
